spring:
  application:
    name: CONFIG
#github仓库地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abcdtianzi/config-repo
          username: abcdtianzi
          password: ting27924757
          basedir: /Users/ting/IdeaProjects/SpringCloud_Sell/config/basedir #该地址为本地仓库
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        exclude: "*"